### ISSUE TITLE
能否出一个Androidx的module

### ISSUE THREAD

**Issue by willflier** [qingmei2/DslViewPagerAdapter#1]

**Comment by qingmei2** [comment]
@willflier 

这个repo比较简单，可能考虑以后进行重构，短期不考虑修改，建议作为工具类直接复制源码修改

**Comment by willflier** [comment]
> @willflier
> 
> 这个repo比较简单，可能考虑以后进行重构，短期不考虑修改，建议作为工具类直接复制源码修改
嗯嗯，就是这么弄的
